### ISSUE TITLE
Cannot find webdriver if it's a variable of superclass

### ISSUE THREAD

**Issue by rouke-broersma** [yev/seleniumMvnScreenshot#1]
The ScreenshotListener could not find my webdriver instance because I inherit it from my abstract superclass, I fixed this by adding a method getDriver to my superclass which is used only by the ScreenshotListener as my webdrivers are passed to my tests through parameters. You might want to add this to your readme, or patch the addon to be able to find fields in superclasses.

**Comment by yev** [comment]
Thank you @Mobrockers I'll definitely patch the source and build an updated version.

**Comment by yev** [comment]
@Mobrockers just to inform you that I have released a new version of the seleniumMvnScreenshot plugin with some fixes.

**Comment by rouke-broersma** [comment]
@yev thank you I'll check it out after my vacation :)
